### ISSUE TITLE
High-Res Images Are Being Compressed Down And Saved With Poor, Pixelated Quality

### ISSUE THREAD

**Issue by khafa100** [chapmanu/dimensions#29]
Story: https://trello.com/c/SmeqyxJL

**THE STEPS I TOOK APPROACHING THIS STORY ARE AS FOLLOWS**

I was not provided the original photos attached to this story, so I've been using the following photo and cropping it down to Cascade's Primary Personnel Region dimensions of 120 x 150 to test out possible fixes:

- https://obamawhitehouse.archives.gov/sites/whitehouse.gov/files/images/Administration/People/president_official_portrait_hires.jpg

I did some digging of recent commits but couldn't identify any commit that might have caused this issue, and it's not clear when exactly this started happening. I've even referenced the following pull request for a possible solution: https://github.com/chapmanu/dimensions/pull/15

Based on that I noticed our `croppie.js` is version 2.4.1 so I tried updating it to version 2.5.0 from the following repository, but that didn't fix things either.

- https://github.com/Foliotek/Croppie

Lastly I explored Foliotek's issues for hints but the only thing I came up with is that it's sort of customization or something on our end in `dimensions.js`, so I still believe it's possible to fix this once the root cause is identified.

**HOW I PLAN TO PROCEED FROM HERE**

The requirements of the story state to either fix the issue or provide a resource to reduce the image size. For now I'm going to switch to looking into providing a resource to reduce the size and see if that works. If I have time after then I'll actually fix the issue, otherwise I'll create a follow up story.

**Comment by tatwell** [comment]
👍  I like that test photo. Good choice. Are you able to reproduce the issue with that photo?

**Comment by khafa100** [comment]
Yes, I'm able to reproduce it exactly like in the story. I'm now resizing the photo to smaller resolutions in photoshop and then cropping it in dimensions to see what's the maximum resolution we can crop without the pixelation issue.

**Comment by khafa100** [comment]
I've tested out a few different dimensions and while it's still a bit pixelated, reducing images down to either ~800x640 or ~400x320 gives the best results. I'll get the product owner's opinion on this. I'm also thinking that it's best to only enforce the size limit when trying to crop for images smaller than 400x400. We don't run into the pixelation issue when cropping at 400x400 or above, regardless of the original image size.

I've provided examples below of cropping down to 120x150 from 1920x1537, 1024x820, 800x641 and 400x320:

**Cropped from 1920x1537**
![from 1920](https://user-images.githubusercontent.com/21699957/31733132-980d4aec-b3ef-11e7-85d5-f17f416032b2.jpeg)

**Cropped from 1024x820**
![from 1024](https://user-images.githubusercontent.com/21699957/31733150-a28c4b58-b3ef-11e7-87a7-98eb45092579.jpeg)

**Cropped from 800x641**
![from 800](https://user-images.githubusercontent.com/21699957/31733165-adf9d44c-b3ef-11e7-9733-4e77bb00d1c3.jpeg)

**Cropped from 400x320**
![from 400](https://user-images.githubusercontent.com/21699957/31734000-25b536aa-b3f2-11e7-8f4f-4b6be4c15a7e.jpeg)

**Comment by tatwell** [comment]
@khafa100 This is a good test to run by the product owner for establishing the limit. 

I think it will make life easier for us going forward if we establish some kind of limit. It should be based either on image dimensions or image file size.

Can you add image file size to the examples above?

Also, it is possible for our code to reject images submitted based either on image size or dimensions? If so, ask the product owners which metric they would prefer.

**Comment by khafa100** [comment]
I updated the examples and did a simple test in `dimensions.js` based on the image dimensions (That's what the product owner decided to base the limit on) and it's possible. All I did was show an alert warning the user to reduce the image, instead of a pop-up cropped image, when the user clicks `Crop Image` and when the original image height is bigger than what I allowed for cropping under a height of 400 pixels.

All I need to do now is find a simple online tool for users to reduce image size without sacrificing quality too much.

**Comment by tatwell** [comment]
@khafa100 Popups are ok. An error message would be preferred. Are we displaying any other errors on this site? If so, how are they handled?

Do not bother finding an online tool. There probably isn't a simple online tool that does this and I'd hate to refer users to some malware site. Just recommend they use photoshop or gimp (as free alternative).

**Comment by khafa100** [comment]
I used alert since we already use an alert message when a user tries to click on preset values but their original image is too small. I'll be showing that in my pull request but I can change to an error message if you want.

They said the main users don't have photoshop but I'm fine with gimp. Either way I'll just be suggesting a tool for the user in the alert message.
